# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "0 0 * * 6"
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Reason for running workflow'     
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Switch to master
      uses: srt32/git-actions@v0.0.3
      with: 
        args: git switch -c ${{ steps.extract_branch.outputs.branch }}
    - name: Update submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --remote --merge
    - name: Git status
      uses: srt32/git-actions@v0.0.3
      with:
        args: git status
    - name: Commit submodule update
      uses: test-room-7/action-update-file@v1
      with:
        file-path: static/content/docs
        commit-msg: ":construction_worker: github action submodule auto update"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-dot: true
        
